name: glow
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.3.0+1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  enefty_icons: ^1.0.7
  google_generative_ai: ^0.4.6
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.2.1
  enhance_stepper: ^1.0.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  hive: ^2.2.3
  sembast: ^3.8.4
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  syncfusion_flutter_datepicker: ^28.2.9
  loading_animation_widget: ^1.3.0
  path: ^1.9.1
  syncfusion_flutter_calendar: ^28.2.12
  intl: ^0.20.2
  equatable: ^2.0.7
  dot_navigation_bar: ^1.0.2
  dio: ^5.8.0+1
  geolocator: ^14.0.0
  skeletonizer: ^2.0.1
  flutter_swipe_action_cell: ^3.1.5
  reactive_forms: ^18.0.0
  slang: ^4.7.2
  flutter_localization: ^0.3.2
  slang_flutter: ^4.7.0
  dartz: ^0.10.1
  flutter_floating_bottom_bar: ^1.3.0
  home_widget: ^0.8.0



dev_dependencies:

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter



  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  slang_build_runner: ^4.4.0
  auto_route_generator: ^9.0.0
  hive_generator: ^2.0.1



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - key.env
    - assets/prompts/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lilita
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 500
        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Condensed-Light.ttf
        - asset: assets/fonts/Roboto_Condensed-Medium.ttf
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
